### ISSUE TITLE
upload demo videos

### ISSUE THREAD

**Issue by Lyken17** [NVlabs/VILA#1]
https://github.com/Efficient-Large-Model/VILA/assets/7783214/80c47742-e873-4080-ad7d-d17c4700539f

https://github.com/Efficient-Large-Model/VILA/assets/7783214/6079374c-0787-4bc4-b9c6-e1524b4c9dc4

**Comment by hzhang57** [comment]
Thank you for fantastic demo, would the script vila_demo.py be released @Lyken17

**Comment by Lyken17** [comment]
Our demo is supported by tinychat and awq. @ys-2020  can comment how to reproduce

**Comment by ys-2020** [comment]
Thanks for your interest in VILA and TinyChat! Please follow the instructions [here](https://github.com/mit-han-lab/llm-awq/tree/main/tinychat#usage) for reproduction.
