### ISSUE TITLE
Inference has error: TypeError: LlamaForCausalLM.forward() got an unexpected keyword argument 'seqlens_in_batch'

### ISSUE THREAD

**Issue by hzhang57** [NVlabs/VILA#10]
I test the inference cmd: 
 python -W ignore llava/eval/run_llava.py     --model-path Efficient-Large-Model/VILA-7B     --conv-mode vicuna_v1     --query "<image>\n Please describe the traffic condition."     --image-file "demo_images/av.png"
and encounter errors of: 

1. VILA/llava/model/language_model/llava_llama.py", line 125, in forward
    outputs = super().forward(
TypeError: LlamaForCausalLM.forward() got an unexpected keyword argument 'seqlens_in_batch'

It also shows warning message that the some VILA layers are not loaded:
2. Loading checkpoint shards: 100%|██████████████| 3/3 [00:04<00:00,  1.38s/it]Some weights of the model checkpoint at Efficient-Large-Model/VILA-7B were not used when initializing LlavaLlamaForCausalLM: ['model.vision_tower.vision_tower.vision_model.encoder.layers.10.self_attn.k_proj.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.13.mlp.fc1.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.23.mlp.fc2.bias', 'model.vision_tower.vision_tower.vision_model.encoder.lay.....

Is there anyway to fix this inference problem?

**Comment by hzhang57** [comment]
cp -rv ./llava/train/transformers_replace/* ~/anaconda3/envs/vila/lib/python3.10/site-packages/transformers/models/
 
solve my problem,

**Comment by shikhar-srivastava** [comment]
> It also shows warning message that the some VILA layers are not loaded: 
> 2. Loading checkpoint shards: 100%|██████████████| 3/3 [00:04<00:00, 1.38s/it]Some weights of the model checkpoint at Efficient-Large-Model/VILA-7B were not used when initializing LlavaLlamaForCausalLM: ['model.vision_tower.vision_tower.vision_model.encoder.layers.10.self_attn.k_proj.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.13.mlp.fc1.weight', 'model.vision_tower.vision_tower.vision_model.encoder.layers.23.mlp.fc2.bias', 'model.vision_tower.vision_tower.vision_model.encoder.lay.....



@hzhang57 Was the `cp -rv ./llava/train/transformers_replace/* ~/anaconda3/envs/vila/lib/python3.10/site-packages/transformers/models/` able to solve the above VILA layer loading warning (point 2) as well?

**Comment by hzhang57** [comment]
I also have the warnings, I guess this is correct ? @Lyken17 
I tried do run the evaluation script ./eval_textvqa.sh, also get these warnings, but get expected metric: 63.97 for VILA-13B

**Comment by Lyken17** [comment]
the warnings should be safe to ignore.
