### ISSUE TITLE
Is there any way to increase the context window?

### ISSUE THREAD

**Issue by ZackBradshaw** [NVlabs/VILA#100]
```Token indices sequence length is longer than the specified maximum sequence length for this model (356885 > 4096). Running this sequence through the model will result in indexing errors```

**Comment by osttkm** [comment]
Did you find any solution about this problem?

**Comment by ZackBradshaw** [comment]
No I just just cleaned my data better still having loads of other issues
finetuning this but I've since then have switched models and am reworking
the data set.

**Comment by osttkm** [comment]
Thank you for your reply. 
It seems that the only option is to delete the relevant data from the JSON file. Thank you for sharing.

**Comment by Lyken17** [comment]
We will release a long-context version soon. Please stay tuned.

**Comment by osttkm** [comment]
@Lyken17 
Thank you, I'm looking forward to it.
