### ISSUE TITLE
How do we run the video caption demo as in the README page?

### ISSUE THREAD

**Issue by rebuttalpapers** [NVlabs/VILA#11]
Can we use some pre-trained model instead of GPT-3/4 to run the video caption demo?
Can you provide the code for running the video caption demo?
How do we call this file? if we want to customized prompts and models.
https://github.com/NVlabs/VILA/blob/48aadd55c450b182f82f88ad340800428fa3a161/llava/eval/model_vqa_videodemo.py

What is the options for the input of the function? https://github.com/NVlabs/VILA/blob/48aadd55c450b182f82f88ad340800428fa3a161/llava/eval/model_vqa_videodemo.py#L143

Thanks!

**Comment by Efficient-Large-Language-Model** [comment]
You can try:

python -W ignore llava/eval/run_vila.py \
    --model-path Efficient-Large-Model/VILA1.5-3b \
    --conv-mode vicuna_v1 \
    --query "<video>\n Please describe this video." \
    --video-file "demo.mp4"

**Comment by yaolug** [comment]
Could you try the following?

python -W ignore llava/eval/run_vila.py \
    --model-path Efficient-Large-Model/VILA1.5-3b \
    --conv-mode vicuna_v1 \
    --query "<video>\n Please describe this video." \
    --video-file "demo.mp4"

**Comment by rebuttalpapers** [comment]
Thanks!

**Comment by Lyken17** [comment]
Hi there,

Our team has moved our VILA to a new location: [NVLabs/VILA](https://github.com/NVlabs/VILA). We kindly request that you update your references to the old repository location with the new one (e.g, git clone / pipeline integration). This will ensure that you have access to the latest updates, improvements, and bug fixes for VILA project. Current repo will be archieved in one week (Jul 10th) and made private after one month (Aug 4th).

Thank you for your understanding and continued support. If your issue still exists, feel free to open a new one in the new place. We appreciate your patience and cooperation during this transition.

Best regards,
VILA Team
