### ISSUE TITLE
KeyError: 'llava_llama'

### ISSUE THREAD

**Issue by huzicong** [NVlabs/VILA#11]
When I ran vila's demo, I ran into the bug below：
![image](https://github.com/Efficient-Large-Model/VILA/assets/101184592/6d22f592-2cff-4e48-94c3-4cbe889884b3)

**Comment by Lyken17** [comment]
it seems you haven't follow the full installation instructions of VILA

https://github.com/Efficient-Large-Model/VILA/blob/main/environment_setup.sh

```
pip install git+https://github.com/huggingface/transformers@v4.36.2
cp -r ./llava/train/transformers_replace/* ~/anaconda3/envs/vila/lib/python3.10/site-packages/transformers/models/
```

**Comment by Lyken17** [comment]
Assuming the issue is resolved, close for now. Feel free to re-open it.
