### ISSUE TITLE
[HELP] Do we have any docker image for Jetson platform ? 

### ISSUE THREAD

**Issue by lenoardshannon** [NVlabs/VILA#111]
Hi Yaolug

We have been working on how to train VILA in Jetson Orin and it's turns out that I have updated my ORIN to Jetpack 6 enviroment. 
I don't find any tourial to setup in Jetpack 6 environment. It's still be very annoying to find the responding libraries. So, do we have any related docker image for VILA this project on Jetson ?

Thanks,
Best regards

Leonard

**Comment by Lyken17** [comment]
so far we didn't prepare docker for jetson, we only have docker for x86 server.

**Comment by dusty-nv** [comment]
Hi @lenoardshannon, you can find various components in [jetson-containers ](https://github.com/dusty-nv/jetson-containers) for building the VILA repo with the needed dependencies on Jetson.  I haven't done a container for the VILA repo directly, as we have other inferencing containers for VILA (like from [Live Llava](https://www.jetson-ai-lab.com/tutorial_live-llava.html)) - but I am also interested to try VILA fine-tuning (LORA).  If you try it let us know how it goes 👍
