### ISSUE TITLE
Is stage2 neccessary?

### ISSUE THREAD

**Issue by peibinchen** [NVlabs/VILA#12]
To validate the effectiveness of the second stage, I remove the second stage and directly train the third stage after completing the first stage. The zero-shot metrics are as follows:
MME: 1457.42/306.43
MMBench-CN: 61.77
MMBench: 68.9
GQA: 61.93
The overall metrics being slightly lower than those mentioned in the paper, but with no significant difference. Considering the resource consumption of the second stage, can I conclude that the second stage is relatively less useful for zero-shot?

**Comment by shikhar-srivastava** [comment]
@peibinchen That's interesting. To be sure, can you share the commands you've used, so others can reproduce/test this effect? 
Have you tried evaluating the 4-shot metrics? A primary benefit of the Stage-2 training (on the interleaved image-text corpus) is the benefit to the in-context learning. A smaller impact to the Zero-shot performance is expected.

**Comment by Lyken17** [comment]
This is interesting. Could you share your training setting (and wandb curve if possible) so we can cross-check?

From our experience, the pre-training phase boosts the performance of both zero-shot and in-context learning.

**Comment by Li-Qingyun** [comment]
> @peibinchen That's interesting. To be sure, can you share the commands you've used, so others can reproduce/test this effect? Have you tried evaluating the 4-shot metrics? A primary benefit of the Stage-2 training (on the interleaved image-text corpus) is the benefit to the in-context learning. A smaller impact to the Zero-shot performance is expected.

Agree. But the few-shot evaluation which reveals the in-context learning ability has not been available in this repo.

**Comment by peibinchen** [comment]
@Lyken17 In 3_sft.sh, just set the model_name_or_path to vicuna-7b-v1.5 and pretrain_mm_mlp_adapter to the STAGE1 mm_project folder.

**Comment by Li-Qingyun** [comment]
> @Lyken17 In 3_sft.sh, just set the model_name_or_path to vicuna-7b-v1.5 and pretrain_mm_mlp_adapter to the STAGE1 mm_project folder.

Did your also use vicuna-7b-v1.5 when you pretrained your mm_mlp_adapter in STAGE1?
Seems that your experiment is similar with Llava-1.5 baseline.

The authors used llama2-7b-hf which is not tuned with text-only instrustion data as vicuna.

**Comment by yaolug** [comment]
stage2 will be very helpful for
1. push the performance of benchmark to be even higher (you can eval all benchmark and see the difference)
2. have good multi-image performance, there are some examples in the inference_test folder you can try your model w/o stage2, it will be pretty bad
3. provide better 0-shot capability in real world (that is not reflected very well in the benchmarks), we demonstrated VILA-2.7B on Jetson Orin Nano (https://www.jetson-ai-lab.com/tutorial_nano-vlm.html) at GTC this year, stage 2 is very crucial for real world demo purpose

However, if you don't care about the above 3, you can skip stage2 and yes it will save a lot of compute!
