### ISSUE TITLE
FlashAttention Bug

### ISSUE THREAD

**Issue by rzyfrank** [NVlabs/VILA#13]
When I run the inference code, it reports the error "RuntimeError: FlashAttention only supports Ampere GPUs or newer."

My GPU is V100, how can I not use flash-attention?

**Comment by Li-Qingyun** [comment]
V100s are Tesla architecture, not Ampere GPUs. You may require A100s.

**Comment by rzyfrank** [comment]
Can I not use flash-attention in Inference?

**Comment by Li-Qingyun** [comment]
ok just remove flash-attn-related codes.

**Comment by Lyken17** [comment]
For llama based models, FlashAttn requires >V100 >A6000 GPUs to run because of SRAM limit. 

You may change the flash attn related codes to better adapt your hardware. For inference, our sister project https://github.com/mit-han-lab/llm-awq provides a good support for vila (both quantize and fp16).

**Comment by DwanZhang-AI** [comment]
I mute all the flash_attention_2, it still tells me that the model is using flash_attention_2

**Comment by NuyoaHygge** [comment]
> I mute all the flash_attention_2, it still tells me that the model is using flash_attention_2

/hetu_group/huangkangwei/anaconda3/envs/vila/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py 第608-609行的注释交换一下

**Comment by NuyoaHygge** [comment]
> I mute all the flash_attention_2, it still tells me that the model is using flash_attention_2

lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py Lines 608-609, swap the annotation.
