### ISSUE TITLE
About the inference on video.

### ISSUE THREAD

**Issue by trinhvg** [NVlabs/VILA#134]
./scripts/v1_5/eval/video_chatgpt/run_benchmark_1_correctness.sh 
==> output:
python3: can't open file '/data1/trinh/code/ViLa/image_text/VILA_0820/llava/eval/video/run_inference_benchmark_general.py': [Errno 2] No such file or directory

There is no "run_inference_benchmark_general.py'

should I use "llava/eval/model_vqa_video.py" instead?
Thank you.

**Comment by Davidup1** [comment]
No difference
