### ISSUE TITLE
VILA-1.5-HD coming soon?

### ISSUE THREAD

**Issue by collinmccarthy** [NVlabs/VILA#137]
Hello, will we see VILA "HD" models that support dynamic high resolution ("anyres" padding technique), like we see in LLaVA 1.6? 

If not, do you have any other recommendations on how to use the existing checkpoints with high(er)-resolution images? e.g. 640x640 or more.

**Comment by Efficient-Large-Language-Model** [comment]
Yes, we will have HD version soon
