### ISSUE TITLE
Base LLM for the VILA 7B Model

### ISSUE THREAD

**Issue by shikhar-srivastava** [NVlabs/VILA#14]
Hey folks! 
Great work with VILA. Super helpful!

I'm wondering what the base LLM for the VILA 7B model is? Can you point to the HF pertained model for it?
Specifically for the checkpoints in HF: Efficient-Large-Model/VILA-7b

Thanks!

**Comment by Lyken17** [comment]
We are using LLama-2-7b for the base model. https://huggingface.co/meta-llama/Llama-2-7b

**Comment by shikhar-srivastava** [comment]
Thanks @Lyken17! 
Great work again.
