### ISSUE TITLE
Suspicious a mistake in llava.data.data_mixture

### ISSUE THREAD

**Issue by PeiMing1998** [NVlabs/VILA#14]
The dataset_name in llava/data/data_mixture.py is not coherent with that in /scripts/v1_5/release/8b/1_mm_align.sh
#### in data_mixture.py
``` python 
def register_datasets_mixtures():

    # Align
    llava_1_5_mm_align = Dataset(
        dataset_name='llava_1_5_align', 
        dataset_type='torch',
        data_path='./playground/data/LLaVA-Pretrain/LLaVA-CC3M-Pretrain-595K.json',
        image_path='./playground/data/LLaVA-Pretrain/images'
    )
    add_dataset(llava_1_5_mm_align)
```
####  in 8b/1_mm_align.sh
```base 
torchrun --nnodes=$n_node --nproc_per_node=8 --master_port=25001 \
    --master_addr $MASTER_ADDR --node_rank=$CURRENT_RANK \
    llava/train/train_mem.py \
    --deepspeed ./scripts/zero2.json \
    --model_name_or_path $BASE_MODEL_PATH \
    --version plain \
    --data_mixture llava_1_5_mm_align \
    --vision_tower google/siglip-so400m-patch14-384 \
```

**Comment by yaolug** [comment]
Thanks! Fixed.

**Comment by PeiMing1998** [comment]
Ok！

**Comment by Lyken17** [comment]
Hi there,

Our team has moved our VILA to a new location: [NVLabs/VILA](https://github.com/NVlabs/VILA). We kindly request that you update your references to the old repository location with the new one (e.g, git clone / pipeline integration). This will ensure that you have access to the latest updates, improvements, and bug fixes for VILA project. Current repo will be archieved in one week (Jul 10th) and made private after one month (Aug 4th).

Thank you for your understanding and continued support. If your issue still exists, feel free to open a new one in the new place. We appreciate your patience and cooperation during this transition.

Best regards,
VILA Team
