### ISSUE TITLE
How to inference with AWQ in linux shell.

### ISSUE THREAD

**Issue by GitMonkey0** [NVlabs/VILA#144]
when running the following codes:

_CUDA_VISIBLE_DEVICES=1 python -W ignore llava/eval/run_vila.py \
--model-path VILA1.5-13b-AWQ \
--conv-mode llama_3 \
--query "<image>\n What happened to this image?" \
--image-file "../remote/VILA/demo_images/demo.jpg"_

i got a problem:

_FileNotFoundError: No such file or directory: "VILA1.5-13b-AWQ/llm/model-00001-of-00006.safetensors"_

i noticed that the weights of VILA1.5-13b-AWQ is vila-1.5-13b-w4-g128-awq-v2.pt, how can i use the same codes below to run on a linux servers?

**Comment by danigarciaoca** [comment]
Hi! How did you manage to fix it?

**Comment by jhjangjh** [comment]
I got same issue. How did you fix it?
