### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fakerybakery** [NVlabs/VILA#15]
Hi,
Thanks so much for releasing VILA! Was looking for a ~3B model to fine tune for a while and this looks like a great fit! Do you know if there are any plans to switch the model licenses to a more permissive one? (And does the license apply to fine tunes as well?) Wanted to release my fine tune under an open source license.
Thanks!

**Comment by Lyken17** [comment]
Our code was under Apache 2.0 licenses which should be quite open and flexibile.

For trained weights,  it has to be non-commerical due to some policies. An alternative option is to follow the instruction and train one by your own. The whole training receipt and settings have been avaliable.

**Comment by fakerybakery** [comment]
Makes sense, thanks!
