### ISSUE TITLE
A possible mistake in all sft.sh like ./scripts/v1_5/release/3b/3_sft.sh

### ISSUE THREAD

**Issue by PeiMing1998** [NVlabs/VILA#15]
The cmd line for SFT stage in `readme.md` is:
```bash
bash scripts/v1_5/paper/3_sft.sh [STAGE2_PATH] [OUTPUT_NAME]
```
In file  ./scripts/v1_5/release/3b/3_sft.sh, the `BASE_MODEL_PATH` should be substituted with `STAGE2_PATH`???
```bash
n_nodes=1
bs=16
# OUTPUT of stage 2 script
STAGE2_PATH=$1
# Final output checkpoint path
OUTPUT=$2

torchrun --nnodes=$n_node --nproc_per_node=8 --master_port=25001 \
    --master_addr $MASTER_ADDR --node_rank=$CURRENT_RANK \
    llava/train/train_mem.py \
    --deepspeed ./scripts/zero3.json \
    --model_name_or_path $BASE_MODEL_PATH \  ## The line I cannot understand 
    --version v1 \
    --data_mixture sharegpt4v_gpt4_100k+llava_instruct+sharegpt4v_sft+dvqa_train_200k+chartqa_train_18k+ai2d_train_12k+docvqa_train_10k+geoqa+synthdog_en+vflan+shot2story_shotonly+video_chatgpt+youcook2+vatex+sharegpt_video+scienceqa+wit_subset+math+sherlock \
    --vision_tower google/siglip-so400m-patch14-384 \
    --mm_vision_select_feature cls_patch \
    --mm_projector mlp_downsample \
```

**Comment by yaolug** [comment]
You are right. Fixed.

**Comment by Lyken17** [comment]
Hi there,

Our team has moved our VILA to a new location: [NVLabs/VILA](https://github.com/NVlabs/VILA). We kindly request that you update your references to the old repository location with the new one (e.g, git clone / pipeline integration). This will ensure that you have access to the latest updates, improvements, and bug fixes for VILA project. Current repo will be archieved in one week (Jul 10th) and made private after one month (Aug 4th).

Thank you for your understanding and continued support. If your issue still exists, feel free to open a new one in the new place. We appreciate your patience and cooperation during this transition.

Best regards,
VILA Team
