### ISSUE TITLE
What is NVILA in the leaderboard of Video-MME?

### ISSUE THREAD

**Issue by lntzm** [NVlabs/VILA#154]
Hi Authors,
In the leaderboard of [Video-MME](https://video-mme.github.io/home_page.html#leaderboard), there is an NVILA ranked 8th, which links to this repo. I wonder which version of VILA is NVILA and can achieve the performance as reported in the leaderboard.

![image](https://github.com/user-attachments/assets/83ec1518-b95b-4342-8be3-c82dbafe0316)

**Comment by Lyken17** [comment]
Hi @lntzm , NVILA (a.k.a VILA 2.0) is a new series of VILA models which we are going to release soon. Techinical report and model weights will come within a week.

**Comment by lntzm** [comment]
Thanks a lot.
