### ISSUE TITLE
The suitable frame num when inferencing with VILA1.5-40B (Video description)

### ISSUE THREAD

**Issue by Hasuer** [NVlabs/VILA#155]
I use the following command to describe video using VILA1.5-40b:

```
python -W ignore llava/eval/run_vila.py \
    --model-path Efficient-Large-Model/VILA1.5-40b \
    --conv-mode hermes-2 \
    --query "<video>\n Elaborate on the visual and narrative elements of the video in detail." \
    --num-video-frames 6 \
    --video-file "path/to/pexels_17431740_5.mp4"
```

When "num-video-frames " is 6, It can output a good description:

"The video begins with a view of the back of a person wearing a beige coat with a fur-lined hood, walking up a stone staircase. The person is carrying a back pack and is surrounded by other individuals also ascending the stairs. The environment suggests a serene, possibly sacred location, with stone lanterns and traditional Japanese architectural elements visible. The camera angle is from behind the person in the beige coat, and the focus is on the movement up the stairs. The color palette is muted, with earthy tones of the stone and the natural greenery surrounding the area."

But if I change the num-video-frames from 6 to 16, the output is terrible for this video, only output one character "9". 

Beside, I have a bunch of video for video description task, all works well when I set num-video-frames=16 for VILA1.5-3b, Llama-3-VILA1.5-8b and VILA1.5-13b. But when it comes to VILA1.5-40b, it crushed for most videos. Dose anyone know the reason?

**Comment by Lyken17** [comment]
This is likely you have exceed the maximum length of VILA. Please set frames <= 10 for VILA 1.5

**Comment by Hasuer** [comment]
> This is likely you have exceed the maximum length of VILA. Please set frames <= 10 for VILA 1.5

Thank! I notice that for  VILA1.5-40b, the frames will be resized to "448" with patch_size=14. So a frame will counts 256 tokens, and 16 frames with extra user prompt will exceed the 4096 context window of VILA1.5. So just making sure the tokens shorter than 4096 will work fine for VILA1.5-40b?

For example, I set num-video-frames=15 or VILA1.5-40b with a short prompt, making sure not exceeding the maximum length of VILA, and I find the generation is quite good. 

So is setting frames <= 10 obligatory or just not exceeding the maximum length is ok?

**Comment by Lyken17** [comment]
> Thank! I notice that for VILA1.5-40b, the frames will be resized to "448" with patch_size=14. So a frame will counts 256 tokens, and 16 frames with extra user prompt will exceed the 4096 context window of VILA1.5. So just making sure the tokens shorter than 4096 will work fine for VILA1.5-40b?

That's right

> So is setting frames <= 10 obligatory or just not exceeding the maximum length is ok?

not exceeding the maximum length should be fine
