### ISSUE TITLE
When will the fp8 training code in the NVILA  be released?

### ISSUE THREAD

**Issue by daixiangzi** [NVlabs/VILA#156]

**Comment by Lyken17** [comment]
The techinique part code is already released at https://github.com/NVlabs/COAT

The full scripts with NVILA will be released next week.

**Comment by daixiangzi** [comment]
> The techinique part code is already released at https://github.com/NVlabs/COAT
> 
> The full scripts with NVILA will be released next week.

ok ，thank you
