### ISSUE TITLE
How was youCook2 pre-processed?

### ISSUE THREAD

**Issue by MohammedSB** [NVlabs/VILA#19]
Hello,

For youCook2, it seems like you guys have a folder called video_data_clipped in which pre-processed videos are in.
For example, for the video with ID 5olHoTWB1Hw, you have multiple separate clips: 5olHoTWB1Hw_1, 5olHoTWB1Hw_2, etc, shown in the JSON file obtained from here https://github.com/NVlabs/VILA/tree/main/data_prepare.

Is the script for generating these clips shared anywhere, because I can't seem to find it?
Downloading youCook2 directly from the source only downloads the entire video.

Thanks.

**Comment by yaolug** [comment]
We cannot share the video files. However, we didn't do anything fancy. Just some re-encoding of the video files to make sure it can be read.

**Comment by MohammedSB** [comment]
Hi Yaolug,
Thanks for your reply.

We don't need the video files, but I still don't understand what the different clips are. For example, what are 5E3kulJRzGY_0.mp4, 5E3kulJRzGY_1.mp4, 5E3kulJRzGY_2.mp4, etc. 5E3kulJRzGY.mp4 is a 5-minute video downloaded from the original source. How are these separate clips of 5E3kulJRzGY.mp4 made?

**Comment by XueFuzhao** [comment]
Hi, in the original youcook2 video annotation file, there is a label "segment": [114, 127] for each caption. You can use this to clip the video into different clips.

**Comment by Lyken17** [comment]
Hi there,

Our team has moved our VILA to a new location: [NVLabs/VILA](https://github.com/NVlabs/VILA). We kindly request that you update your references to the old repository location with the new one (e.g, git clone / pipeline integration). This will ensure that you have access to the latest updates, improvements, and bug fixes for VILA project. Current repo will be archieved in one week (Jul 10th) and made private after one month (Aug 4th).

Thank you for your understanding and continued support. If your issue still exists, feel free to open a new one in the new place. We appreciate your patience and cooperation during this transition.

Best regards,
VILA Team
