### ISSUE TITLE
Multi-image Input Inference Script

### ISSUE THREAD

**Issue by gaozhihan** [NVlabs/VILA#20]
I've successfully tested multi-image input inference as mentioned in https://github.com/Efficient-Large-Model/VILA/issues/8#issuecomment-1998852303 
```
python -W ignore llava/eval/run_llava.py --model-path Efficient-Large-Model/VILA-7B --conv-mode vicuna_v1 --query "<image> image 1 is google, famous for its search engine. <image> image 2 is microsoft, framous for its operating system. <image> image 3 is apple, famous for iPhone and Mac. <image> image 4 is" --image-file "demo_images/g.PNG,demo_images/m.PNG,demo_images/a.PNG,demo_images/n.PNG"
```
It works perfectly! 
I want to inquire if there is a script that can perform this inference on a whole custom dataset? If so, what format should the custom data be in?

**Comment by adithyakvh** [comment]
Can you share the link from where you downloaded the model weights?

**Comment by yaolug** [comment]
@gaozhihan You can look at our eval scripts and use the same data formats.

@adithyakvh see https://huggingface.co/Efficient-Large-Model
