### ISSUE TITLE
does VILA-1.5 40B finetuned on video tasks? why the video benchmark is also very strong?

### ISSUE THREAD

**Issue by dragen1860** [NVlabs/VILA#20]
hi, 
     I noticed in some video benchmark ,such as MMBench, MM Vet, Video MME， the performance of VILA 40B is also very competitve. But from the original paper, both in projector init/pretraining/SFT, it only use interleaved image-text training dataset. I wonder why it behaves so good on video? Thank you

**Comment by yaolug** [comment]
Yes, we added some video SFT data. 
See https://github.com/NVlabs/VILA/tree/main/data_prepare
and example scripts: https://github.com/NVlabs/VILA/blob/main/scripts/v1_5/release/40b/3_sft.sh#L26
