### ISSUE TITLE
vila 40b video inference scripts?

### ISSUE THREAD

**Issue by dragen1860** [NVlabs/VILA#21]
HI, dear author: 
  I find the 3b video inferece scripts is as 
```
python -W ignore llava/eval/run_vila.py \
    --model-path Efficient-Large-Model/VILA1.5-3b \
    --conv-mode vicuna_v1 \
    --query "<video>\n Please describe this video." \
    --video-file "demo.mp4"
```

1. could you provide  video inference scripts for  40b models? 
2. does single H100 80GB support 40b inference?

Thank you.

**Comment by yaolug** [comment]
You can try 

python -W ignore llava/eval/run_vila.py \
    --model-path Efficient-Large-Model/VILA1.5-40b \
    --conv-mode hermes-2 \
    --query "<video>\n Please describe this video." \
    --video-file "demo.mp4"

**Comment by Lyken17** [comment]
Hi there,

Our team has moved our VILA to a new location: [NVLabs/VILA](https://github.com/NVlabs/VILA). We kindly request that you update your references to the old repository location with the new one (e.g, git clone / pipeline integration). This will ensure that you have access to the latest updates, improvements, and bug fixes for VILA project. Current repo will be archieved in one week (Jul 10th) and made private after one month (Aug 4th).

Thank you for your understanding and continued support. If your issue still exists, feel free to open a new one in the new place. We appreciate your patience and cooperation during this transition.

Best regards,
VILA Team
