### ISSUE TITLE
More data leading to lower indicators?

### ISSUE THREAD

**Issue by uniquehou** [NVlabs/VILA#22]
Hi, I tried VILA-13B, training an image classification task, with good results, but now I'm running into a problem.
Before I used 250k data (finetune lora), the precision went up with more training data. Later, we added 200k data and the indicator dropped by 6-7% instead.
We are now basically sure that the new data distribution is the same as before, so what else could be the reason for the decline?

**Comment by yaolug** [comment]
The performance when fine-tuning w/ lora is not guaranteed. We normally do a stage3 finetuning w/ both our default data and the new data.

**Comment by Griffintaur** [comment]
How does this piece of code doesn't throw index error ?
` info = self.data_list[i - self.idx_offset]`
here the self.data_list is the subset of the whole dataset while `i` is over the whole dataset now  how does it handle if i is beyond the length of the dataset?

**Comment by Lyken17** [comment]
which dataset do you use? This is old implementation and should be deprecated now. @Griffintaur
