### ISSUE TITLE
Intermediate stages checkpoints

### ISSUE THREAD

**Issue by sarvghotra** [NVlabs/VILA#23]
Hi there,

Thanks for opensourcing the checkpoints and the code.

For research purposes, having access to stage-0 and stage-1 intermediate checkpoints will be really useful. Are you planning to release them too, if not done already?

**Comment by yaolug** [comment]
We will release those in our next release, stay tuned.

**Comment by HiHiAllen** [comment]
Same request. Looking forward to it !
