### ISSUE TITLE
what does `repack_multimodal_data` mean?

### ISSUE THREAD

**Issue by dragen1860** [NVlabs/VILA#25]
Hi, dear author:
   During your code, you used `repack_multimodal_data` to reduce computation. But this technology is relatively new to me, could you give some documents or links to illustrate how does it work? thank you.

**Comment by Lyken17** [comment]
This is a basically a padding strategy to accelerate training.

Consider 4 data samples with max 256 input length
<100 tokens>
<75 tokens>
<50 tokens>
<25 tokens>

it can be actually merged to 

<100 tokens> <sep> <25 tokens>
<75 tokens> <sep> <50 tokens>

thus reducing batchsize from 4 to 2, leading to faster training.

**Comment by Lyken17** [comment]
Hi there,

Our team has moved our VILA to a new location: [NVLabs/VILA](https://github.com/NVlabs/VILA). We kindly request that you update your references to the old repository location with the new one (e.g, git clone / pipeline integration). This will ensure that you have access to the latest updates, improvements, and bug fixes for VILA project. Current repo will be archieved in one week (Jul 10th) and made private after one month (Aug 4th).

Thank you for your understanding and continued support. If your issue still exists, feel free to open a new one in the new place. We appreciate your patience and cooperation during this transition.

Best regards,
VILA Team
