### ISSUE TITLE
Missing deepspeed config files in training scripts

### ISSUE THREAD

**Issue by AoyuQC** [NVlabs/VILA#27]
Hi,

 I am trying to reproduce the results. However, both the zero2 and zero3 config files are missing in the project. Can you please upload these files to the scripts folder. Thank you!

**Comment by Lyken17** [comment]
Apologies for the missing files. I have uploaded them to the main.

**Comment by Lyken17** [comment]
https://github.com/Efficient-Large-Model/VILA/commit/eaadb1e55a088978ce06abb6242edc251fb4665a
