### ISSUE TITLE
Model checkpoints before supervised fine-tuning

### ISSUE THREAD

**Issue by CRazorback** [NVlabs/VILA#28]
Thank you for your fantastic work.

Is there any plan to release the pre-trained model checkpoints before SFT for both VILA7B and VILA13B? It would be helpful to evaluate its performance at some other tasks.

I appreciate your help and look forward to hearing back from you.

**Comment by Lyken17** [comment]
for sure, we have released here https://huggingface.co/collections/Efficient-Large-Model/vila-15-checkpoints-intermediate-6674dd0c20ff491d38f8299d

Also please be noted that the repo is being deprecated. We are moving to [NVlabs/VILA](https://github.com/NVlabs/VILA) for  further discussion.

**Comment by ruojinhhhhhh** [comment]
> for sure, we have released here https://huggingface.co/collections/Efficient-Large-Model/vila-15-checkpoints-intermediate-6674dd0c20ff491d38f8299d
> 
> Also please be noted that the repo is being deprecated. We are moving to [NVlabs/VILA](https://github.com/NVlabs/VILA) for further discussion.

hi, this collection is empty. Will you release checkpoints before SFT in future? Thanks a lot~
