### ISSUE TITLE
video data format to fine-tune the model

### ISSUE THREAD

**Issue by JunMa11** [NVlabs/VILA#3]
Thanks for sharing the amazing work!

I'd like to fine-tune the 3B model on my own video dataset but I don't know how to prepare the data.

Would it be possible to share an example of **video data format** for using this script?

https://github.com/NVlabs/VILA/blob/main/scripts/v1_5/release/3b/3_sft.sh

How long does it take for the supervised fine-tuning process of 3B model on a `8A100` node?

**Comment by Efficient-Large-Language-Model** [comment]
You can take a look at https://github.com/NVlabs/VILA/tree/main/data_prepare
For example, follow the example of Youcook2 to prepare your data.

Funetuning time depends on how many data you have. If finetuning 1M video samples on 8A100 w/ 3B model, I think it will take a few hours.

**Comment by JunMa11** [comment]
Thanks for your guidance very much!

**Comment by hkunzhe** [comment]
@Efficient-Large-Language-Model @JunMa11 Should SFT be based on the pre-trained model obtained from the second stage? When will the pre-trained models be released?

**Comment by Lyken17** [comment]
Hi there,

Our team has moved our VILA to a new location: [NVLabs/VILA](https://github.com/NVlabs/VILA). We kindly request that you update your references to the old repository location with the new one (e.g, git clone / pipeline integration). This will ensure that you have access to the latest updates, improvements, and bug fixes for VILA project. Current repo will be archieved in one week (Jul 10th) and made private after one month (Aug 4th).

Thank you for your understanding and continued support. If your issue still exists, feel free to open a new one in the new place. We appreciate your patience and cooperation during this transition.

Best regards,
VILA Team
