### ISSUE TITLE
Request for middle checkpoint

### ISSUE THREAD

**Issue by jihaonew** [NVlabs/VILA#42]
Thank you for the amazing release!

Do you plan to release the checkpoints from different stages, e.g., checkpoint before SFT? These checkpoints would be valuable for further fine-tuning.

**Comment by Lyken17** [comment]
@yaolug as discussed earlier, can we also open source the middle checkpoints?

**Comment by Efficient-Large-Language-Model** [comment]
Yes, will do.

**Comment by jihaonew** [comment]
Thank you! 👀
