### ISSUE TITLE
Which data is multiple images input?

### ISSUE THREAD

**Issue by lucasjinreal** [NVlabs/VILA#5]
Hi, which part data used in training provide multiple image inputs, and how does the image context learning achieved?

**Comment by yaolug** [comment]
mmc4 dataset have multiple images. The in context learning is mainly achieved by mmc4 dataset

**Comment by lucasjinreal** [comment]
hi, do u have a preprocessed mmc4 dataset to download? like llava style format.

**Comment by yaolug** [comment]
mmc4 cannot be changed to llava format. It is not QA. Please follow https://github.com/Efficient-Large-Model/VILA/tree/main/data_prepare and our code supports training from it.

**Comment by Lyken17** [comment]
close for now, feel free to re-open if necessary.

**Comment by Lyken17** [comment]
Hi there,

Our team has moved our VILA to a new location: [NVLabs/VILA](https://github.com/NVlabs/VILA). We kindly request that you update your references to the old repository location with the new one (e.g, git clone / pipeline integration). This will ensure that you have access to the latest updates, improvements, and bug fixes for VILA project. Current repo will be archieved in one week (Jul 10th) and made private after one month (Aug 4th).

Thank you for your understanding and continued support. If your issue still exists, feel free to open a new one in the new place. We appreciate your patience and cooperation during this transition.

Best regards,
VILA Team
