### ISSUE TITLE
How's the DownSampleBlock performance compare with CAbstractor?

### ISSUE THREAD

**Issue by lucasjinreal** [NVlabs/VILA#55]
How's the DownSampleBlock performance compare with CAbstractor?

**Comment by Efficient-Large-Language-Model** [comment]
Could you give a reference to CAbstractor

**Comment by lucasjinreal** [comment]
Oh, it's HoneybeeChat

**Comment by Efficient-Large-Language-Model** [comment]
Could you send a link?

**Comment by Lyken17** [comment]
close due to inactivity. feel free to re-open when necessary.
