### ISSUE TITLE
When will new annotations files be available?

### ISSUE THREAD

**Issue by hubenjm** [NVlabs/VILA#57]
In new v1.5 version of https://github.com/Efficient-Large-Model/VILA/blob/main/data_prepare/README.md
there are links to new dataset annotation files such as
`huggingface-cli download mit-han-lab/vila-dataset youcook_filtered_v3.json --repo-type dataset --local-dir youcook2 --local-dir-use-symlinks False`
which are not publicly accessible at this time. Any guess as to if or when it will be possible to retrieve files from the `mit-han-lab/vila-dataset` repository?

**Comment by Lyken17** [comment]
now should be public. Please let us know if any further issues.
