### ISSUE TITLE
Any plan to release VILA 1.5 paper?

### ISSUE THREAD

**Issue by JihwanEom** [NVlabs/VILA#6]

**Comment by yaolug** [comment]
The technical details are still covered pretty well by the original paper https://arxiv.org/abs/2312.07533
Note that we made Section 4.4 the default now.

**Comment by dragen1860** [comment]
what does 1.5 updates compared with original 1.0 paper?  simple replaced with llama3 llm? @yaolug thx.

**Comment by yaolug** [comment]
1. We tried a bunch of combination of LLM & vision encoder and provide the best combination of our findings for each size. You can refer to https://github.com/NVlabs/VILA/tree/main/scripts/v1_5/release for the details
2. We use Section 4.4 as default
3. We improved pretrain and SFT datasets mixture

**Comment by Lyken17** [comment]
close for now, feel free to re-open if necessary.

**Comment by Lyken17** [comment]
Hi there,

Our team has moved our VILA to a new location: [NVLabs/VILA](https://github.com/NVlabs/VILA). We kindly request that you update your references to the old repository location with the new one (e.g, git clone / pipeline integration). This will ensure that you have access to the latest updates, improvements, and bug fixes for VILA project. Current repo will be archieved in one week (Jul 10th) and made private after one month (Aug 4th).

Thank you for your understanding and continued support. If your issue still exists, feel free to open a new one in the new place. We appreciate your patience and cooperation during this transition.

Best regards,
VILA Team
