### ISSUE TITLE
What is the LLM used for VILA 1.5 40B?

### ISSUE THREAD

**Issue by javier-m** [NVlabs/VILA#63]
I understand that Llama 2 models were used for VILA, but only 7B, 13B and 70B models were released. As for Llama 3, only the 7B and the 70B models were released. However the licence only list the Llama licence, and there is nothing in the model card.

Which LLM was used as a foundation of VILA 40B?

**Comment by Efficient-Large-Language-Model** [comment]
https://huggingface.co/NousResearch/Nous-Hermes-2-Yi-34B
