### ISSUE TITLE
VILA-1.5 details

### ISSUE THREAD

**Issue by Lopa07** [NVlabs/VILA#67]
- Where can I found the paper for VILA-1.5?
- What visual encodes and LMs are used for VILA 1.5 3B, 8B, 13B, and 40B?

**Comment by hkunzhe** [comment]
You can look at the model configuration files on Hugging Face or the training code in the repository.

**Comment by Lopa07** [comment]
Sorry, I can not find these details. It will be very helpful, if you please post these information here for better visibility.

**Comment by yaolug** [comment]
You can look at the training scripts under https://github.com/Efficient-Large-Model/VILA/tree/main/scripts/v1_5/release
You can refer to the technical details from the original paper. https://arxiv.org/pdf/2312.07533
We made Section 4.4 the default now.

**Comment by Lopa07** [comment]
Thank you both! This helped.
