### ISSUE TITLE
About VILADistributedSampler and gradient_accumulation_steps

### ISSUE THREAD

**Issue by dreamerlin** [NVlabs/VILA#69]
If we use the VILADistributedSampler (https://github.com/Efficient-Large-Model/VILA/blob/main/llava/train/llava_trainer.py#L274-L281) for Distributed Training, should the `gradient_accumulation_steps` be hardcoded to 1? Since I notice that when I use 4 nodes (8 GPUs per node) to training, and set gradient_accumulation_steps to 8, the speed is fast but I think it is abnormal.

**Comment by yaolug** [comment]
We have tried gradient_accumulation_steps to be 2 and 4 and it seems reasonable.

**Comment by Griffintaur** [comment]
@yaolug VilaDistributedSampler doesnt ensure that all the process across the batch have indices from the same dataset? Will it not cause an issue in zero3 configuration when different processes have different batch sizes considering the pertraining stage when img-caption datasset are always `n_sample_index'* train batch size while interleaved data is just composed of batch size?

**Comment by Lyken17** [comment]
close due to inactivity. feel free to reopen if necessary
