### ISSUE TITLE
About the VideoQA dataset

### ISSUE THREAD

**Issue by Yxxxb** [NVlabs/VILA#7]
Thanks for amazing work!

I found in your paper that VILA use several QA dataset(including MSVD-QA...) during the ablation study.
I wonder if the released model Efficient-Large-Model/VILA-7b on huggingface has been trained with these QA SFT dataset.
Thanks!

**Comment by Lyken17** [comment]
Hi Xubing 

Theses models are not trained on Video datasets. You may refer to https://github.com/Efficient-Large-Model/VILA/tree/main/data_prepare for dataset matrix.

**Comment by Yxxxb** [comment]
thanks for your reply and work.
