### ISSUE TITLE
Any plan to support ollama?

### ISSUE THREAD

**Issue by lingxuan630** [NVlabs/VILA#7]

**Comment by Lyken17** [comment]
no plan so far. As ollama currently focuses on text-only llm

**Comment by Lyken17** [comment]
close for now, feel free to re-open if more comments.

**Comment by Lyken17** [comment]
Hi there,

Our team has moved our VILA to a new location: [NVLabs/VILA](https://github.com/NVlabs/VILA). We kindly request that you update your references to the old repository location with the new one (e.g, git clone / pipeline integration). This will ensure that you have access to the latest updates, improvements, and bug fixes for VILA project. Current repo will be archieved in one week (Jul 10th) and made private after one month (Aug 4th).

Thank you for your understanding and continued support. If your issue still exists, feel free to open a new one in the new place. We appreciate your patience and cooperation during this transition.

Best regards,
VILA Team
