### ISSUE TITLE
Bug in conversation.py

### ISSUE THREAD

**Issue by zhang-jr** [NVlabs/VILA#71]
A minor bug was found here. It seems the `assistant`role  in [`conversation.py`](https://github.com/Efficient-Large-Model/VILA/blob/44a4cca98ac0f81b0891eb2341e9826b5553b6e8/llava/conversation.py#L440) is faulty. It should be `<|start_header_id|>assistant<|end_header_id|>\n\n`.

**Comment by yaolug** [comment]
Thanks! We will fix in the next version.

**Comment by Lyken17** [comment]
close for now. The fix is expected to deliver on Aug.
