### ISSUE TITLE
Question about the output

### ISSUE THREAD

**Issue by DwanZhang-AI** [NVlabs/VILA#77]
<img width="1258" alt="image" src="https://github.com/Efficient-Large-Model/VILA/assets/25074067/49a936fd-8106-41a1-ac93-eab2f0ade288">

This is the output of the model.

python -W ignore llava/eval/run_vila.py  \
        --model-path Efficient-Large-Model/Llama-3-VILA1.5-8b  \
        --conv-mode llama_3  \
        --query "<image>\n Please describe the traffic condition." \
        --image-file "demo_images/av.png" 
        
This is the inference code. Why the output is wrong?

**Comment by DwanZhang-AI** [comment]
BTW, I have muted the flash attention module.

**Comment by Lyken17** [comment]
seems works properly on my side, should not be a issue for flash-attn. Could you make sure you have done a fresh install following readme?

**Comment by vedernikovphoto** [comment]
> BTW, I have muted the flash attention module.

Hi, can you please explain how did you turn it off? I have V100 and can't run with "flash attention" On. Thanks!

**Comment by liuyijiang1994** [comment]
same problem

**Comment by Lyken17** [comment]
Close due to inacitivity. We haven't fully tested VILA on old hardware.
