### ISSUE TITLE
The inference video reports an error： ValueError: Unable to create tensor, you should probably activate padding with 'padding=True' to have batched tensors with the same length.

### ISSUE THREAD

**Issue by changqinyao** [NVlabs/VILA#78]

**Comment by oroojlooy** [comment]
Same here with trying `python -W ignore llava/eval/run_vila.py     --model-path Efficient-Large-Model/Llama-3-VILA1.5-8b     --conv-mode llama_3     --query "<image>\n Please describe the traffic condition."     --image-file "demo_images/av.png"`

**Comment by oroojlooy** [comment]
The issue is `numpy 2.0.0`. Using `1.x.x` version fixes the issue: `pip install numpy==1.26.4`

**Comment by liuyijiang1994** [comment]
thx!
