### ISSUE TITLE
Having trouble running multi-image input inference.

### ISSUE THREAD

**Issue by HiHiAllen** [NVlabs/VILA#8]
Thank you for your excellent work. I encountered a problem when running multi-image input inference locally. After briefly looking at your code, I modified the inference command as follows:
`python -W ignore llava/eval/run_llava.py \
    --model-path /path/workspace/VILA_13B \
    --conv-mode llava_llama_2 \
    --image-file "/cfs-allenxmzhu/workspace/VILA/demo_images/av.png,/cfs-allenxmzhu/workspace/VILA/inference_test/test_data/flying_chair.png" \
    --query "<image-placeholder> <image-placeholder> Please describe the two images separately."`
    
During testing, I found that the model often does not output results, but only outputs a newline character (or possibly a space). 
Is this command correct ?
Also, I currently do not have `tinychat` library installed, and I am not considering the convenience brought by 4-bit quantization for now. Would not using `tinychat` library cause the problem I encountered?

**Comment by CiaoHe** [comment]
Same issue. I tried to put three images (with 3 <image-placeholder>) but just get a '\n'.

**Comment by hzhang57** [comment]
I run the "google, microsoft, apple, nvidida" examples usting the command:

`python -W ignore llava/eval/run_llava.py     --model-path Efficient-Large-Model/VILA-7B     --conv-mode vicuna_v1     --query "<image> image 1 is google, famous for its search engine. <image> image 2 is microsoft, framous for its operating system. <image> image 3 is apple, famous for iPhone and Mac. <image> image 4 is"     --image-file "demo_images/g.PNG,demo_images/m.PNG,demo_images/a.PNG,demo_images/n.PNG"`

it produces:   nvidia, famous for its graphics processing unit.

![gitc](https://github.com/Efficient-Large-Model/VILA/assets/38028090/4d197a9a-1191-4943-9a9c-f3f4e6fe104d)

**Comment by HiHiAllen** [comment]
@hzhang57  Thank you for sharing, yes, the point is --conv-mode needs to be set to vicuna_v1 or vicuna_v1_nosys.
@CiaoHe Sorry I forgot to reply, I looked at the author's code earlier, and here --conv-mode needs to be set to vicuna_v1 or vicuna_v1_nosys. Not llava_llama_2.
