### ISSUE TITLE
Whether this is a bug?

### ISSUE THREAD

**Issue by jihaonew** [NVlabs/VILA#80]
[llava_arch](https://github.com/NVlabs/VILA/blob/87f58b9be19bb5243af425761e01cf01cbd16778/llava/model/llava_arch.py#L570C13-L570C36)

In the function repack_multimodal_data, it seems that you may pack several sequences into one to save memory. However, you don't update the variable ``sorted_seqlens_in_batch`` after packing. It is a bug or I miss something? 

Thank you.

**Comment by Lyken17** [comment]
In our training pipeline current implementation works well. But it may break the function in the future transformers. Good point. Will fix in the revision

**Comment by yaolug** [comment]
What do you mean by not updating?
It's updated here https://github.com/NVlabs/VILA/blob/87f58b9be19bb5243af425761e01cf01cbd16778/llava/model/llava_arch.py#L500

**Comment by jihaonew** [comment]
Yes. But you reorg the data in L509-L539 and don't update the sorted_seqlens_in_batch accordingly.

**Comment by yaolug** [comment]
Ln509-Ln539 does not rearrange, it just cut it in rows. So the order is the same.

**Comment by jihaonew** [comment]
What you do in L509-L539 is to pack short examples into one example if I understand it correctly. 
For example, let's say you have 3 examples with sequence lengths of [3, 3, 100] and the sorted_seqlens_in_batch here is [100, 3, 3]. After packing, you will merge the first two samples into one, thus the sequence lengths become [6, 100], but the sorted_seqlens_in_batch is still [100, 3, 3] since you don't update it.

**Comment by yaolug** [comment]
In your example, initially example is [3, 3, 100], and seqlens_in_batch is [3, 3, 100]
sorted_seqlens_in_batch will be sorted in Ln500 and become [100, 3, 3]
Later Ln 509- Ln 539 example will be packed and sorted into [100, 6] and sorted_seqlens_in_batch is [100, 3, 3]

You can use https://github.com/NVlabs/VILA/blob/main/tests/gpu_tests/test_packing.py this test to understand it better.

**Comment by jihaonew** [comment]
Thanks for the explanation. I've checked the implementation below 
https://github.com/NVlabs/VILA/blob/0085724ca3363dc62eaa0d7ef1a30ad20df5c8da/llava/train/transformers_replace/models/llama/modeling_llama.py#L53

And I think you are right.
