### ISSUE TITLE
Seems video token isn't used in the model during video inference

### ISSUE THREAD

**Issue by Virtualexistence** [NVlabs/VILA#87]
Great work! I just have a question/doubt on using the `<video>` token in the video inference. 
The constants defined don't seem to recognise any video token but only image tokens: https://github.com/NVlabs/VILA/blob/0085724ca3363dc62eaa0d7ef1a30ad20df5c8da/llava/constants.py#L27

Am I missing something or does the model take `<video>` as just text context while the image token is added automatically N times i.e. length of frames to the query?
https://github.com/NVlabs/VILA/blob/0085724ca3363dc62eaa0d7ef1a30ad20df5c8da/llava/eval/run_vila.py#L66

`python -W ignore llava/eval/run_vila.py \
    --model-path Efficient-Large-Model/VILA1.5-3b \
    --conv-mode vicuna_v1 \
    --query "<video>\n Please describe this video." \
    --video-file "demo.mp4"`

**Comment by Lyken17** [comment]
You are right, current open source version does not handle the <video> properlly. Please replace it with 8 <image> instead. We will fix it in next release.

**Comment by Virtualexistence** [comment]
Aw, it's still a great repository. Thank you for reply!
