### ISSUE TITLE
Does VILA support higher resolution than 336px, e.g., 672 or 1008? 

### ISSUE THREAD

**Issue by lalalal9797** [NVlabs/VILA#91]
It seems that the supported resolution is the same as "data_args.image_processor.crop_size" in the code, and I wonder whether VILA supports higher resolution than 336px, e.g., 672 or 1008? Thanks!

**Comment by Lyken17** [comment]
enforcing diffrent resolutions on vit may lead to performance degrade and we haven't test that yet.

Baifeng @bfshi has some experience applying S2 on higher resolution settings and can comment more on this.

**Comment by bfshi** [comment]
Hi @lalalal9797, yes VILA w/ S2 supports higher resolution. S2 is an efficient way to scale up any vision model to higher resolution (see [here](https://github.com/bfshi/scaling_on_scales)). Currently we've released the checkpoint of VILA1.5-3B-S2 ([here](https://huggingface.co/Efficient-Large-Model/VILA1.5-3b-s2)). It supports resolution of 768. Please see the benchmark results in README.
