### ISSUE TITLE
How to convert model to gguf

### ISSUE THREAD

**Issue by dand-milestone** [NVlabs/VILA#93]
Hey there,

my goal is to run VILA-7b on a jetson device through Ollama. As far as I could see there’s no “out-of-the-box” support to convert the model weights into the .gguf format without losing its vision component. I did some digging and found the /app/examples/convert_legacy_llama.py from llama.cpp but it still doesn’t do the trick for the vision tower.

Maybe I’m being ignorant about some obvious solution but so far I couldn’t get around to it. Any ideas how to convert the model properly?

Any pointers, guides, tutorials etc. to achieve the above goal will be much appreciated!

**Comment by Lyken17** [comment]
we haven't tried ollama yet. Im afraid you may need to ask in ollama community for support

**Comment by dand-milestone** [comment]
Fair, thanks for the quick response! 
Is there any experience on how to convert VILA-7b to the .gguf format you could share?

**Comment by Lyken17** [comment]
not either, current we use tensorRT for efficient inference.
