### ISSUE TITLE
Whether the visual encoder participates in training

### ISSUE THREAD

**Issue by LoverLost** [NVlabs/VILA#95]
In the 3rd stage, following your paper 'Finally, we further perform instruction tuning of the pre-trained model on visual language instruction datasets,' I'm wondering if siglip is also unfrozen and involved in the training during this stage. Or is it only the projector and LLM?

**Comment by LoverLost** [comment]
If possible, I would also like to know which version of llama is used for the LLM of the 3b model?

**Comment by Lyken17** [comment]
ViT was during vila training. 

For 3b, we used shearedllama from princeton.

**Comment by Lyken17** [comment]
https://huggingface.co/princeton-nlp/Sheared-LLaMA-2.7B
