### ISSUE TITLE
Support for multi-video captioning with multiple grid image inputs?

### ISSUE THREAD

**Issue by YoungjaeDev** [NVlabs/VILA#96]
Hello, I'm interested in using VILA for multi-video captioning. I'm wondering if it's possible to input multiple grid images (8 to 16 frames each), each representing a different video, for simultaneous processing and captioning

Is it possible?

**Comment by Lyken17** [comment]
while you can try on [vila.mit.edu](https://vila.mit.edu/), i am afraid that performance may not be ideal since VILA is not finetuned on such instruction / formats.

**Comment by Lyken17** [comment]
feel free to reopen if necessary.
