### ISSUE TITLE
release schedule for the "VILA1.5-34b-4bit-AWQ" model.

### ISSUE THREAD

**Issue by xiexiaoshinick** [NVlabs/VILA#99]
We are excited to announce that VILA1.5 has achieved the top position on both the MMMU leaderboard and the Video-MME leaderboard, solidifying its status as the best open-sourced Vision-Language Model (VLM) available. This milestone underscores the advanced capabilities and performance of VILA1.5 in multimodal understanding and video-language tasks.

We are eager to know the release schedule for the "VILA1.5-34b-4bit-AWQ" model. Could you please provide an update on when this model will be open-sourced? Any details regarding the timeline and availability would be greatly appreciated.

Thank you!

**Comment by Lyken17** [comment]
The name is later updated to vila-1.5-40b, which is already released at https://huggingface.co/Efficient-Large-Model/VILA1.5-40b-AWQ
